import type { NextPage } from "next";
import Head from "next/head";
import SearchCharacter from "../components/SearchCharachter";
import Header from "../components/Header";
import EpickDetail from "../components/epicdetail";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DUNLINE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <SearchCharacter />
      </main>
    </div>
  );
};

export default Home;
