import { useState } from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";

import SearchForm from "../components/Search/SearchForm";
import CharacterList from "../components/Search/CharacterList";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string | null>(null);

  return (
    <>
      <Head>
        <title>DUNLINE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box
        as="header"
        minWidth="320px"
        textAlign="center"
        padding="20px 0"
        fontSize="6xl"
      >
        <h1>DUNLINE</h1>
      </Box>
      <Box
        as="main"
        minWidth="320px"
        maxWidth="800px"
        height="100%"
        margin="0 auto"
        padding="0 20px"
      >
        <SearchForm
          handleSubmit={(url) => {
            setUrl(url);
          }}
        />
        <CharacterList url={url} />
      </Box>
    </>
  );
};

export default Home;
