import { useState } from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Link from "next/link";
import Image from "next/image";
import styled from "@emotion/styled";

import SearchForm from "../components/Search/SearchForm";
import CharacterList from "../components/Search/CharacterList";
import Header from "../components/Header";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string | null>(null);

  return (
    <>
      <Head>
        <title>DUNLINE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Box
        as="main"
        minWidth="320px"
        maxWidth="800px"
        height="70vh"
        margin="0 auto"
        padding="0 20px"
      >
        <SearchForm
          handleSubmit={(url) => {
            setUrl(url);
          }}
        />
        <CharacterList url={url} />
      </Box>
      <Box
        as="footer"
        minWidth="320px"
        maxWidth="800px"
        margin="0 auto"
        padding="0 20px"
      >
        <Box display="flex" justifyContent="space-around">
          <Link
            href="https://developers.neople.co.kr"
            passHref
            prefetch={false}
          >
            <StyledImage
              src="/images/df_Logo.png"
              alt="df API LOGO"
              width="200px"
              height="35px"
            />
          </Link>
          <Link
            href="https://open.kakao.com/o/s3Dh8Afe"
            passHref
            prefetch={false}
          >
            <a>
              <StyledImage
                src="/images/kakao.png"
                alt="Kakao Open Talk"
                width="50px"
                height="50px"
              />
            </a>
          </Link>
        </Box>
      </Box>
    </>
  );
};

export default Home;

const StyledImage = styled(Image)`
  cursor: pointer;
`;
